core/urls.py
from django.urls import path, re_path, include
from . import views
from rest_framework import routers
from rest_framework.documentation import include_docs_urls

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'contacts', views.ContactViewSet)
router.register(r'departments', views.DepartmentViewSet)
router.register(r'doctors', views.DoctorViewSet)
router.register(r'patients', views.PatientViewSet)
router.register(r'hospitals', views.HospitalViewSet)
router.register(r'dayschedule', views.DayScheduleViewSet)
router.register(r'appointment', views.AppointmentViewSet)
router.register(r'notifications', views.NotificationViewSet)

urlpatterns = [
    path('testUI/', views.testUI, name='testUI'),
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('signup/patient', views.signup_patient, name='signup_patient'),
    path('signup/doctor', views.signup_doctor, name='signup_doctor'),
    path('signup/hospital', views.signup_hospital, name='signup_hospital'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('dashboard/patient', views.dashboard_patient, name='dashboard_patient'),
    path('dashboard/doctor', views.dashboard_doctor, name='dashboard_doctor'),
    path('dashboard/hospital', views.dashboard_hospital, name='dashboard_hospital'),
    path('appointment/book', views.book_appointment, name='book_appointment'),
    path('appointment/filter', views.filter_appointment, name='filter_appointment'),
    path('appointment/calendar', views.calendar_appointment, name='calendar_appointment'),
    path('appointment/upcoming', views.upcoming_appointment, name='upcoming_appointment'),
    path('doctor/leave', views.doctor_leave, name='doctor_leave'),
    path('doctor/leave/reschedule', views.doctor_leave_after, name='doctor_leave_after'),
    path('notifications', views.notifications, name='notifications'),
    path('faq', views.faq, name='faq'),
    path('legal', views.legal, name='legal'),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/docs/', include_docs_urls(title='UPCHAAR API', public=False)),
    path('api/login/', views.api_login, name='api_login'),
    path('api/logout/', views.api_logout, name='api_logout'),
    path('api/auth-token/', views.get_auth_token, name='api_auth_token'),
    path('api/send-sms/', views.send_sms, name='api_send_sms'),
    path('api/send-notification/', views.send_notification, name='api_send_notification'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('core.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.conf import settings


class User(AbstractUser):
    PATIENT = 1
    DOCTOR = 2
    HOSPITAL = 3
    ADMIN = 4
    ROLE_CHOICES = (
        (PATIENT, 'Patient'),
        (DOCTOR, 'Doctor'),
        (HOSPITAL, 'Hospital'),
        (ADMIN, 'Admin'),
    )
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, null=True, blank=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.username


class Contact(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='contacts')
    contact_no = models.IntegerField(unique=True)

    def __str__(self):
        return self.contact_no


class Department(models.Model):
    department_name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.department_name


class Doctor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    education = models.CharField(max_length=500)
    time_slot = models.DurationField()

    def __str__(self):
        return self.user.get_full_name()


class Patient(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        return self.user.get_full_name()


class Hospital(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    hospital_name = models.CharField(max_length=100)
    no_of_beds = models.IntegerField()
    latitude = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    longitude = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return self.hospital_name


class DaySchedule(models.Model):
    MONDAY = 1
    TUESDAY = 2
    WEDNESDAY = 3
    THURSDAY = 4
    FRIDAY = 5
    SATURDAY = 6
    SUNDAY = 7
    DAYS = (
        (MONDAY, 'Monday'),
        (TUESDAY, 'Tuesday'),
        (WEDNESDAY, 'Wednesday'),
        (THURSDAY, 'Thursday'),
        (FRIDAY, 'Friday'),
        (SATURDAY, 'Saturday'),
        (SUNDAY, 'Sunday'),
    )
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE)
    day = models.PositiveSmallIntegerField(choices=DAYS)
    time_slot_from = models.TimeField()
    time_slot_to = models.TimeField()


class Appointment(models.Model):
    CONFIRMED = 1
    CANCELLED = 2
    WAITING = 3
    STATUS_CODES = (
        (CONFIRMED, 'Confirmed'),
        (CANCELLED, 'Cancelled'),
        (WAITING, 'Waiting'),
    )
    appointment_date = models.DateField()
    time_slot_from = models.TimeField()
    token_no = models.IntegerField()
    status = models.PositiveSmallIntegerField(choices=STATUS_CODES)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE)


class Notification(models.Model):
    user_id = models.IntegerField()
    message = models.CharField(max_length=1000)
    read = models.BooleanField(default=False)

templates/signup/signup_doctor.html
{% extends 'base.html' %}

{% block main %}
    <div class="container">
        <div class="section">
            <h5 class="center-align grey-text text-darken-1">Signup as Doctor</h5>
        </div>
        <div class="divider"></div>
        <br>
        <div class="container">
            <div class="row">
                <form class="col s12" method="post" action="">
                    {% csrf_token %}
                    {% include 'form_snippet.html' with form=userform %}
                    <div class="row">
                        <div class="input-field col s12">
                            <label for="id_date_of_birth">Date of Birth</label>
                            <input type="text" id="id_date_of_birth" name="date_of_birth" class="datepicker">
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <label for="id_department">Department</label>
                            <input type="text" id="id_department" name="department" class="autocomplete">
                        </div>
                    </div>
                    {% include 'form_snippet.html' with form=doctorform %}
                    <div class="center-align">
                        <button class="btn waves-effect waves-light" type="submit" name="action">Signup</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="section">
            <h6>Already a user? <a href="{% url 'login' %}">Login</a></h6>
        </div>
    </div>

{% endblock %}

{% block custom_script %}
    <script>
        $(document).ready(function(){
            $('.autocomplete').autocomplete({
                data: {
                    {% for department in departments %}
                        {{ department }} : null,
                    {% endfor %}
                },
            });
            $('.datepicker').datepicker({
                format:"yyyy-mm-dd",
            });
        });
    </script>
{% endblock %}

templates/signup/signup_hospital.html
{% extends 'base.html' %}

{% block main %}
    <div class="container">
        <div class="section">
            <h5 class="center-align grey-text text-darken-1">Signup as Hospital Admin</h5>
        </div>
        <div class="divider"></div>
        <br>
        <div class="container">
            <div class="row">
                <form class="col s12" method="post" action="">
                    {% csrf_token %}
                    {% include 'form_snippet.html' with form=userform %}
                    {% include 'form_snippet.html' with form=hospitalform %}
                    <div class="center-align">
                        <button class="btn waves-effect waves-light" type="submit" name="action">Signup</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="section">
            <h6>Already a user? <a href="{% url 'login' %}">Login</a></h6>
        </div>
    </div>

{% endblock %}

{% block custom_script %}
    <script>
        $(document).ready(function(){
            $('.datepicker').datepicker({
                format:"yyyy-mm-dd",
            });
        });
    </script>
{% endblock %}

templates/signup/signup_patient.html
{% extends 'base.html' %}

{% block main %}
    <div class="container">
        <div class="section">
            <h5 class="center-align grey-text text-darken-1">Signup as Patient</h5>
        </div>
        <div class="divider"></div>
        <br>
        <div class="container">
            <div class="row">
                <form class="col s12" method="post" action="">
                    {% csrf_token %}
                    {% include 'form_snippet.html' with form=userform %}
                    <div class="row">
                        <div class="input-field col s12">
                            <label for="id_date_of_birth">Date of Birth</label>
                            <input type="text" id="id_date_of_birth" name="date_of_birth" class="datepicker">
                        </div>
                    </div>
                    {% include 'form_snippet.html' with form=patientform %}
                    <div class="center-align">
                        <button class="btn waves-effect waves-light" type="submit" name="action">Signup</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="section">
            <h6>Already a user? <a href="{% url 'login' %}">Login</a></h6>
        </div>
    </div>

{% endblock %}

{% block custom_script %}
    <script>
        $(document).ready(function(){
            $('.datepicker').datepicker({
                format:"yyyy-mm-dd",
            });
        });
    </script>
{% endblock %}